// Club Management Mock Data
export const mockClubData = {
  club: {
    id: "club-1",
    name: "SSB Garuda Muda",
    founded: 2010,
    city: "Makassar",
    address: "Jl. Hasanuddin No. 123, Makassar",
    phone: "+62-411-1234567",
    email: "contact@garudamuda.id",
    website: "www.garudamuda.id",
    stadium: "Stadion Karebosi",
    colors: ["#063470", "#FFD700"],
    logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=club-1",
    banner: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&h=400",
    status: "Active",
  },

  stats: {
    totalPlayers: 68,
    totalStaff: 15,
    activeCompetitions: 3,
    trainingSessions: 42,
  },

  recentMatches: [
    {
      id: "m1",
      opponent: "FC Makassar",
      date: "2024-03-10",
      result: "2-1",
      homeTeam: true,
      status: "Finished",
    },
    {
      id: "m2",
      opponent: "Persija Muda",
      date: "2024-03-08",
      result: "1-1",
      homeTeam: false,
      status: "Finished",
    },
    {
      id: "m3",
      opponent: "Borneo FC",
      date: "2024-03-05",
      result: "3-0",
      homeTeam: true,
      status: "Finished",
    },
  ],

  upcomingMatches: [
    {
      id: "u1",
      opponent: "SSB Bintang Timur",
      date: "2024-03-15",
      time: "15:00",
      venue: "Lapangan Karebosi",
      competition: "Liga Makassar U13",
    },
    {
      id: "u2",
      opponent: "FC Harapan Jaya",
      date: "2024-03-20",
      time: "14:00",
      venue: "Stadion Utama",
      competition: "Cup Makassar U15",
    },
  ],

  staff: [
    {
      id: "s1",
      name: "Ahmad Yani",
      role: "Head Coach",
      department: "Coaching",
      phone: "+62-812-1234567",
      email: "ahmad@club.id",
      status: "Active",
      joinedAt: "2020-06-15",
    },
    {
      id: "s2",
      name: "Budi Santoso",
      role: "Assistant Coach",
      department: "Coaching",
      phone: "+62-812-2234567",
      email: "budi@club.id",
      status: "Active",
      joinedAt: "2021-01-20",
    },
    {
      id: "s3",
      name: "Dr. Siti Nurhaliza",
      role: "Team Doctor",
      department: "Medical",
      phone: "+62-812-3234567",
      email: "siti@club.id",
      status: "Active",
      joinedAt: "2019-08-01",
    },
    {
      id: "s4",
      name: "Dede Kusuma",
      role: "Physiotherapist",
      department: "Medical",
      phone: "+62-812-4234567",
      email: "dede@club.id",
      status: "Active",
      joinedAt: "2021-03-15",
    },
  ],

  coaches: [
    {
      id: "c1",
      name: "Ahmad Yani",
      license: "UEFA_PRO",
      licenseLevel: "AFC Pro",
      teamAssigned: "U17 Team",
      specialty: "Formation & Tactics",
      experience: 15,
      yearsExperience: 15,
      nationality: "Indonesia",
      email: "ahmad@club.id",
    },
    {
      id: "c2",
      name: "Budi Santoso",
      license: "UEFA_A",
      licenseLevel: "AFC A",
      teamAssigned: "U15 Team",
      specialty: "Player Development",
      experience: 10,
      yearsExperience: 10,
      nationality: "Indonesia",
      email: "budi@club.id",
    },
    {
      id: "c3",
      name: "Eka Wijaya",
      license: "UEFA_B",
      licenseLevel: "AFC B",
      teamAssigned: "U13 Team",
      specialty: "Fitness & Conditioning",
      experience: 7,
      yearsExperience: 7,
      nationality: "Indonesia",
      email: "eka@club.id",
    },
  ],

  medicalStaff: [
    {
      id: "m1",
      name: "Dr. Siti Nurhaliza",
      role: "Team Doctor",
      specialization: "Sports Medicine",
      phone: "+62-812-3234567",
      email: "siti@club.id",
      status: "Active",
    },
    {
      id: "m2",
      name: "Dede Kusuma",
      role: "Physiotherapist",
      specialization: "Injury Rehabilitation",
      phone: "+62-812-4234567",
      email: "dede@club.id",
      status: "Active",
    },
    {
      id: "m3",
      name: "Fajar Rahman",
      role: "Fitness Trainer",
      specialization: "Strength & Conditioning",
      phone: "+62-812-5234567",
      email: "fajar@club.id",
      status: "Active",
    },
  ],

  achievements: [
    { id: "a1", title: "Liga Makassar U13 2022", category: "League", year: 2022 },
    { id: "a2", title: "Cup Makassar U15 2021", category: "Cup", year: 2021 },
    { id: "a3", title: "Youth Championship 2020", category: "Tournament", year: 2020 },
    { id: "a4", title: "Provincial Championship 2019", category: "League", year: 2019 },
  ],

  youthTeams: [
    { id: "yt1", name: "U8 Team", players: 20, coach: "Ahmad Yani", status: "Active" },
    { id: "yt2", name: "U10 Team", players: 22, coach: "Budi Santoso", status: "Active" },
    { id: "yt3", name: "U12 Team", players: 25, coach: "Eka Wijaya", status: "Active" },
    { id: "yt4", name: "U14 Team", players: 24, coach: "Ahmad Yani", status: "Active" },
    { id: "yt5", name: "U16 Team", players: 23, coach: "Budi Santoso", status: "Active" },
    { id: "yt6", name: "U18 Team", players: 21, coach: "Eka Wijaya", status: "Active" },
  ],

  history: [
    { year: 2010, event: "Club founded by youth center initiative" },
    { year: 2012, event: "Won first provincial championship" },
    { year: 2015, event: "Opened new training facilities" },
    { year: 2018, event: "Joined national youth league" },
    { year: 2020, event: "Established academy partnerships" },
    { year: 2023, event: "Won regional youth championship" },
  ],

  activityTimeline: [
    {
      id: "at1",
      action: "Player Registered",
      description: "Rizky Pratama registered as defender",
      timestamp: "2 hours ago",
      type: "player",
    },
    {
      id: "at2",
      action: "Training Session",
      description: "U15 Team completed fitness training",
      timestamp: "4 hours ago",
      type: "training",
    },
    {
      id: "at3",
      action: "Match Result",
      description: "Won 2-1 against FC Makassar",
      timestamp: "1 day ago",
      type: "match",
    },
    {
      id: "at4",
      action: "Staff Joined",
      description: "Ahmad Yani joined as Head Coach",
      timestamp: "3 days ago",
      type: "staff",
    },
  ],

  trainingSessions: [
    {
      id: "ts1",
      date: "2024-03-15",
      time: "09:00",
      duration: 90,
      type: "Tactical",
      focus: "Formation & Positioning",
      coach: "Ahmad Yani",
      location: "Main Pitch",
      team: "Senior Team",
      playerCount: 25,
      status: "Completed",
      objectives: ["Practice 4-3-3 formation", "Improve defensive setup", "Tactical awareness"],
    },
    {
      id: "ts2",
      date: "2024-03-16",
      time: "14:00",
      duration: 60,
      type: "Fitness",
      focus: "Conditioning & Endurance",
      coach: "Eka Wijaya",
      location: "Training Field 2",
      team: "U17 Team",
      playerCount: 18,
      status: "Scheduled",
      objectives: ["Improve cardiovascular fitness", "Sprint work", "Recovery drills"],
    },
    {
      id: "ts3",
      date: "2024-03-17",
      time: "10:00",
      duration: 75,
      type: "Technical",
      focus: "Ball Control & Passing",
      coach: "Budi Santoso",
      location: "Training Field 1",
      team: "U15 Team",
      playerCount: 22,
      status: "Scheduled",
      objectives: ["Improve first touch", "Short passing accuracy", "Movement off the ball"],
    },
    {
      id: "ts4",
      date: "2024-03-14",
      time: "11:00",
      duration: 120,
      type: "Match Prep",
      focus: "Game Strategy",
      coach: "Ahmad Yani",
      location: "Main Pitch",
      team: "Senior Team",
      playerCount: 23,
      status: "Completed",
      objectives: ["Study opponent tactics", "Practice set pieces", "Final match preparation"],
    },
    {
      id: "ts5",
      date: "2024-03-18",
      time: "15:30",
      duration: 45,
      type: "Recovery",
      focus: "Cool Down & Stretching",
      coach: "Dr. Siti Nurhaliza",
      location: "Medical Room",
      team: "Senior Team",
      playerCount: 12,
      status: "Scheduled",
      objectives: ["Post-match recovery", "Injury prevention", "Muscle relaxation"],
    },
  ],

  facilities: [
    {
      id: "f1",
      name: "Main Pitch",
      capacity: 3500,
      condition: "Excellent",
      lastMaintenance: "2024-03-01",
      nextMaintenance: "2024-06-01",
      maintenanceStatus: "Scheduled",
      features: ["Floodlights", "Irrigation system", "Professional grass"],
      bookings: 12,
      status: "Operational",
    },
    {
      id: "f2",
      name: "Training Field 1",
      capacity: 500,
      condition: "Good",
      lastMaintenance: "2024-02-15",
      nextMaintenance: "2024-05-15",
      maintenanceStatus: "Scheduled",
      features: ["Portable goals", "Training cones", "Marking lines"],
      bookings: 28,
      status: "Operational",
    },
    {
      id: "f3",
      name: "Training Field 2",
      capacity: 500,
      condition: "Good",
      lastMaintenance: "2024-02-20",
      nextMaintenance: "2024-05-20",
      maintenanceStatus: "Scheduled",
      features: ["Portable goals", "Training cones"],
      bookings: 25,
      status: "Operational",
    },
    {
      id: "f4",
      name: "Gym",
      capacity: 80,
      condition: "Fair",
      lastMaintenance: "2024-01-30",
      nextMaintenance: "2024-04-30",
      maintenanceStatus: "In Progress",
      features: ["Cardio equipment", "Weights", "Stretching area"],
      bookings: 18,
      status: "Maintenance",
    },
    {
      id: "f5",
      name: "Medical Room",
      capacity: 20,
      condition: "Excellent",
      lastMaintenance: "2024-03-05",
      nextMaintenance: "2024-06-05",
      maintenanceStatus: "Scheduled",
      features: ["Medical beds", "Physiotherapy equipment", "Ice bath"],
      bookings: 35,
      status: "Operational",
    },
    {
      id: "f6",
      name: "Meeting Room",
      capacity: 50,
      condition: "Good",
      lastMaintenance: "2024-02-10",
      nextMaintenance: "2024-05-10",
      maintenanceStatus: "Scheduled",
      features: ["Projector", "Whiteboard", "AV system"],
      bookings: 22,
      status: "Operational",
    },
  ],

  maintenanceHistory: [
    {
      id: "mh1",
      facilityName: "Main Pitch",
      facilityId: "f1",
      date: "2024-03-01",
      type: "Grass cutting and fertilizing",
      duration: 8,
      cost: "Rp 5.000.000",
      status: "Completed",
      notes: "Monthly maintenance completed",
    },
    {
      id: "mh2",
      facilityName: "Gym",
      facilityId: "f4",
      date: "2024-03-12",
      type: "Equipment servicing",
      duration: 6,
      cost: "Rp 3.500.000",
      status: "Completed",
      notes: "Treadmill repair, all weights inspected",
    },
    {
      id: "mh3",
      facilityName: "Medical Room",
      facilityId: "f5",
      date: "2024-03-10",
      type: "Equipment calibration",
      duration: 4,
      cost: "Rp 2.000.000",
      status: "Completed",
      notes: "Ice bath thermostat calibrated",
    },
  ],
};

export const mockPlayerData = {
  players: [
    {
      id: "p1",
      name: "Rizky Pratama",
      position: "Defender",
      number: 4,
      birthDate: "1998-05-15",
      age: 25,
      height: 182,
      weight: 78,
      nationality: "Indonesia",
      status: "Active",
      joinedAt: "2020-01-10",
      nIK: "1234567890123456",
      internationalCaps: 12,
      goals: 2,
      assists: 5,
      appearances: 145,
      photo: "https://placehold.co/300x400/navy/white?text=RizkyPratama",
    },
    {
      id: "p2",
      name: "Andi Kusuma",
      position: "Midfielder",
      number: 8,
      birthDate: "2000-08-20",
      age: 23,
      height: 177,
      weight: 72,
      nationality: "Indonesia",
      status: "Active",
      joinedAt: "2021-06-15",
      nIK: "2345678901234567",
      internationalCaps: 8,
      goals: 15,
      assists: 18,
      appearances: 98,
      photo: "https://placehold.co/300x400/primary/white?text=AndiKusuma",
    },
    {
      id: "p3",
      name: "Budi Santoso",
      position: "Forward",
      number: 9,
      birthDate: "1999-03-10",
      age: 24,
      height: 180,
      weight: 76,
      nationality: "Indonesia",
      status: "Active",
      joinedAt: "2019-08-01",
      nIK: "3456789012345678",
      internationalCaps: 15,
      goals: 42,
      assists: 12,
      appearances: 156,
      photo: "https://placehold.co/300x400/gold/navy?text=BudiSantoso",
    },
    {
      id: "p4",
      name: "Citra Wijaya",
      position: "Goalkeeper",
      number: 1,
      birthDate: "1997-11-25",
      age: 26,
      height: 188,
      weight: 82,
      nationality: "Indonesia",
      status: "Active",
      joinedAt: "2018-07-01",
      nIK: "4567890123456789",
      internationalCaps: 20,
      goals: 0,
      assists: 0,
      appearances: 178,
      photo: "https://placehold.co/300x400/navy/white?text=CitraWijaya",
    },
    {
      id: "p5",
      name: "Dara Kusuma",
      position: "Defender",
      number: 3,
      birthDate: "2001-07-14",
      age: 22,
      height: 179,
      weight: 75,
      nationality: "Indonesia",
      status: "Injured",
      joinedAt: "2022-01-15",
      nIK: "5678901234567890",
      internationalCaps: 5,
      goals: 1,
      assists: 3,
      appearances: 42,
      photo: "https://placehold.co/300x400/navy/white?text=DaraKusuma",
    },
    {
      id: "p6",
      name: "Evan Pratama",
      position: "Midfielder",
      number: 6,
      birthDate: "2002-04-08",
      age: 21,
      height: 175,
      weight: 70,
      nationality: "Indonesia",
      status: "Active",
      joinedAt: "2023-06-01",
      nIK: "6789012345678901",
      internationalCaps: 2,
      goals: 3,
      assists: 6,
      appearances: 28,
      photo: "https://placehold.co/300x400/primary/white?text=EvanPratama",
    },
  ],

  contracts: [
    {
      id: "ct1",
      playerName: "Rizky Pratama",
      playerId: "p1",
      startDate: "2022-01-10",
      endDate: "2026-12-31",
      salary: "Rp 250.000.000",
      status: "Active",
      type: "Professional",
      terms: ["Professional clause", "Championship bonus", "Performance bonus"],
      signedDate: "2021-12-15",
    },
    {
      id: "ct2",
      playerName: "Andi Kusuma",
      playerId: "p2",
      startDate: "2021-06-15",
      endDate: "2025-06-30",
      salary: "Rp 180.000.000",
      status: "Active",
      type: "Professional",
      terms: ["Performance bonus", "Loyalty bonus"],
      signedDate: "2021-05-20",
    },
    {
      id: "ct3",
      playerName: "Budi Santoso",
      playerId: "p3",
      startDate: "2019-08-01",
      endDate: "2027-08-31",
      salary: "Rp 300.000.000",
      status: "Active",
      type: "Professional",
      terms: ["Championship bonus", "Top scorer bonus", "International cap bonus"],
      signedDate: "2019-07-10",
    },
  ],

  disciplineRecords: [
    {
      id: "d1",
      playerName: "Andi Kusuma",
      playerId: "p2",
      offense: "Unsportsmanlike conduct",
      date: "2024-02-15",
      consequence: "Yellow card",
      status: "Resolved",
      matchInfo: "vs FC Bandung",
    },
    {
      id: "d2",
      playerName: "Evan Pratama",
      playerId: "p6",
      offense: "Late arrival to training",
      date: "2024-03-01",
      consequence: "Fine Rp 500.000",
      status: "Resolved",
      matchInfo: "Training session",
    },
    {
      id: "d3",
      playerName: "Rizky Pratama",
      playerId: "p1",
      offense: "Excessive celebration",
      date: "2024-01-20",
      consequence: "Warning",
      status: "Resolved",
      matchInfo: "vs Jakarta FC",
    },
  ],

  injuries: [
    {
      id: "inj1",
      playerName: "Dara Kusuma",
      playerId: "p5",
      injuryType: "Ankle sprain",
      date: "2024-03-10",
      expectedReturn: "2024-04-15",
      status: "Recovery",
      severity: "Moderate",
      treatmentPlan: "Physiotherapy 3x weekly",
      doctor: "Dr. Siti Nurhaliza",
    },
    {
      id: "inj2",
      playerName: "Budi Santoso",
      playerId: "p3",
      injuryType: "Muscle strain",
      date: "2024-02-01",
      expectedReturn: "2024-02-28",
      status: "Recovered",
      severity: "Mild",
      treatmentPlan: "Rest and ice",
      doctor: "Dr. Siti Nurhaliza",
    },
  ],

  documents: [
    {
      id: "doc1",
      playerId: "p1",
      playerName: "Rizky Pratama",
      type: "Passport",
      number: "K1234567",
      issueDate: "2019-05-10",
      expiryDate: "2029-05-10",
      status: "Valid",
      fileName: "passport_rizky.pdf",
    },
    {
      id: "doc2",
      playerId: "p1",
      playerName: "Rizky Pratama",
      type: "Visa",
      number: "VISA-2024-001",
      issueDate: "2024-01-15",
      expiryDate: "2025-01-15",
      status: "Valid",
      fileName: "visa_rizky.pdf",
    },
    {
      id: "doc3",
      playerId: "p1",
      playerName: "Rizky Pratama",
      type: "Contract",
      number: "CT-2022-001",
      issueDate: "2022-01-10",
      expiryDate: "2026-12-31",
      status: "Active",
      fileName: "contract_rizky.pdf",
    },
    {
      id: "doc4",
      playerId: "p2",
      playerName: "Andi Kusuma",
      type: "Work Permit",
      number: "WP-2021-156",
      issueDate: "2021-06-01",
      expiryDate: "2026-06-01",
      status: "Valid",
      fileName: "work_permit_andi.pdf",
    },
  ],

  transfers: [
    {
      id: "tr1",
      playerId: "p3",
      playerName: "Budi Santoso",
      fromClub: "FC Jakarta",
      toClub: "PSMA United",
      transferDate: "2019-08-01",
      transferFee: "Rp 500.000.000",
      type: "Permanent",
      status: "Completed",
    },
    {
      id: "tr2",
      playerId: "p1",
      playerName: "Rizky Pratama",
      fromClub: "Youth Academy",
      toClub: "PSMA United",
      transferDate: "2020-01-10",
      transferFee: "Free",
      type: "Academy",
      status: "Completed",
    },
  ],

  suspensions: [
    {
      id: "sus1",
      playerId: "p2",
      playerName: "Andi Kusuma",
      reason: "Accumulation of yellow cards",
      startDate: "2024-03-15",
      endDate: "2024-03-22",
      matches: 1,
      status: "Active",
    },
  ],

  careerHistory: [
    {
      id: "ch1",
      playerId: "p3",
      year: 2019,
      event: "Joined PSMA United from FC Jakarta",
      type: "Transfer",
    },
    {
      id: "ch2",
      playerId: "p3",
      year: 2020,
      event: "Scored first goal in league",
      type: "Achievement",
    },
    {
      id: "ch3",
      playerId: "p3",
      year: 2022,
      event: "Called up to national team",
      type: "International",
    },
    {
      id: "ch4",
      playerId: "p3",
      year: 2023,
      event: "Became team captain (acting)",
      type: "Achievement",
    },
  ],
};
