import { EligibilityCheckResult } from "../teams/TeamEligibilityChecker";

/**
 * Report Generation Service
 * Handles PDF and CSV export of compliance reports
 */

export interface ReportOptions {
  title: string;
  generatedDate: Date;
  generatedBy?: string;
  competitionName: string;
  format: "csv" | "pdf";
}

// ─── CSV Export ──────────────────────────────────────────────────────
/**
 * Generate CSV report of team eligibility
 */
export function generateCSVReport(
  results: EligibilityCheckResult[],
  options: ReportOptions
): string {
  const lines: string[] = [];

  // Header
  lines.push("Team Eligibility Compliance Report");
  lines.push(`Generated: ${options.generatedDate.toLocaleString()}`);
  lines.push(`Competition: ${options.competitionName}`);
  if (options.generatedBy) {
    lines.push(`Generated By: ${options.generatedBy}`);
  }
  lines.push("");

  // Summary
  const compliant = results.filter((r) => r.compliant).length;
  const total = results.length;
  lines.push(`Summary: ${compliant}/${total} teams compliant (${Math.round((compliant / total) * 100)}%)`);
  lines.push("");

  // Column headers
  lines.push(
    [
      "Team Name",
      "Team ID",
      "Compliant",
      "Completeness %",
      "Issues Count",
      "Issues",
    ].join(",")
  );

  // Data rows
  results.forEach((result) => {
    const issues = result.issues
      .map((i) => `${i.code}: ${i.message}`)
      .join("; ");

    lines.push(
      [
        `"${result.teamName}"`,
        result.teamId,
        result.compliant ? "Yes" : "No",
        result.completeness,
        result.issues.length,
        `"${issues}"`,
      ].join(",")
    );
  });

  lines.push("");
  lines.push("Legend:");
  lines.push("ERROR: Critical issue preventing participation");
  lines.push("WARNING: Issue requiring attention before deadline");
  lines.push("INFO: Information or recommendation");

  return lines.join("\n");
}

/**
 * Download CSV file
 */
export function downloadCSVReport(
  csvContent: string,
  filename: string = `compliance-report-${new Date().getTime()}.csv`
): void {
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);

  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// ─── JSON Export (for further processing) ──────────────────────────
/**
 * Export results as JSON for API integration
 */
export function generateJSONReport(
  results: EligibilityCheckResult[],
  options: ReportOptions
): string {
  const report = {
    metadata: {
      title: options.title,
      format: options.format,
      generatedDate: options.generatedDate.toISOString(),
      generatedBy: options.generatedBy || "system",
      competitionName: options.competitionName,
    },
    summary: {
      total: results.length,
      compliant: results.filter((r) => r.compliant).length,
      withIssues: results.filter((r) => !r.compliant).length,
      compliancePercentage: Math.round(
        (results.filter((r) => r.compliant).length / results.length) * 100
      ),
      averageCompleteness: Math.round(
        results.reduce((sum, r) => sum + r.completeness, 0) / results.length
      ),
    },
    teams: results.map((result) => ({
      id: result.teamId,
      name: result.teamName,
      compliant: result.compliant,
      completeness: result.completeness,
      issues: result.issues.map((i) => ({
        type: i.type,
        code: i.code,
        message: i.message,
        resolution: i.resolution,
      })),
    })),
  };

  return JSON.stringify(report, null, 2);
}

/**
 * Download JSON report
 */
export function downloadJSONReport(
  jsonContent: string,
  filename: string = `compliance-report-${new Date().getTime()}.json`
): void {
  const blob = new Blob([jsonContent], {
    type: "application/json;charset=utf-8;",
  });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);

  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// ─── Summary Report ──────────────────────────────────────────────────
/**
 * Generate text summary of report
 */
export function generateSummaryReport(
  results: EligibilityCheckResult[],
  options: ReportOptions
): string {
  const compliant = results.filter((r) => r.compliant).length;
  const withIssues = results.filter((r) => !r.compliant).length;
  const avgCompleteness = Math.round(
    results.reduce((sum, r) => sum + r.completeness, 0) / results.length
  );

  const errorTeams = results.filter((r) =>
    r.issues.some((i) => i.type === "error")
  );
  const warningTeams = results.filter(
    (r) =>
      r.issues.some((i) => i.type === "warning") &&
      !r.issues.some((i) => i.type === "error")
  );

  let report = "";
  report += `${"=".repeat(60)}\n`;
  report += `TEAM ELIGIBILITY COMPLIANCE REPORT\n`;
  report += `${"=".repeat(60)}\n\n`;

  report += `Competition: ${options.competitionName}\n`;
  report += `Generated: ${options.generatedDate.toLocaleString()}\n`;
  if (options.generatedBy) {
    report += `Generated By: ${options.generatedBy}\n`;
  }
  report += `\n`;

  report += `${"─".repeat(60)}\n`;
  report += `SUMMARY\n`;
  report += `${"─".repeat(60)}\n`;
  report += `Total Teams: ${results.length}\n`;
  report += `✓ Compliant: ${compliant} (${Math.round((compliant / results.length) * 100)}%)\n`;
  report += `⚠ With Issues: ${withIssues} (${Math.round((withIssues / results.length) * 100)}%)\n`;
  report += `Average Completeness: ${avgCompleteness}%\n`;
  report += `\n`;

  report += `${"─".repeat(60)}\n`;
  report += `CRITICAL ISSUES (${errorTeams.length})\n`;
  report += `${"─".repeat(60)}\n`;
  if (errorTeams.length === 0) {
    report += `No critical issues found.\n`;
  } else {
    errorTeams.forEach((team) => {
      report += `\n${team.teamName} (${team.teamId})\n`;
      const errors = team.issues.filter((i) => i.type === "error");
      errors.forEach((issue) => {
        report += `  ✗ ${issue.message}\n`;
        if (issue.resolution) {
          report += `    → ${issue.resolution}\n`;
        }
      });
    });
  }
  report += `\n`;

  report += `${"─".repeat(60)}\n`;
  report += `WARNINGS (${warningTeams.length})\n`;
  report += `${"─".repeat(60)}\n`;
  if (warningTeams.length === 0) {
    report += `No warnings found.\n`;
  } else {
    warningTeams.forEach((team) => {
      report += `\n${team.teamName} (${team.teamId})\n`;
      const warnings = team.issues.filter((i) => i.type === "warning");
      warnings.forEach((issue) => {
        report += `  ⚠ ${issue.message}\n`;
        if (issue.resolution) {
          report += `    → ${issue.resolution}\n`;
        }
      });
    });
  }
  report += `\n`;

  report += `${"─".repeat(60)}\n`;
  report += `ACTION ITEMS\n`;
  report += `${"─".repeat(60)}\n`;

  if (errorTeams.length > 0) {
    report += `1. Resolve critical issues for ${errorTeams.length} team(s) before competition start\n`;
  }
  if (warningTeams.length > 0) {
    report += `2. Address warnings for ${warningTeams.length} team(s) before registration deadline\n`;
  }
  if (avgCompleteness < 100) {
    report += `3. Request additional documentation to reach 100% completeness\n`;
  }

  report += `\n${"=".repeat(60)}\n`;
  report += `End of Report\n`;
  report += `${"=".repeat(60)}\n`;

  return report;
}

/**
 * Get export formats summary
 */
export function getExportFormats() {
  return [
    {
      format: "csv",
      label: "CSV (Spreadsheet)",
      icon: "📊",
      description: "Import into Excel, Google Sheets, or other spreadsheet tools",
    },
    {
      format: "json",
      label: "JSON (Data Exchange)",
      icon: "📄",
      description: "Machine-readable format for API integration and automation",
    },
    {
      format: "text",
      label: "Text (Readable Report)",
      icon: "📋",
      description: "Human-readable text summary with detailed breakdown",
    },
  ];
}
