/**
 * Mock data untuk Competition Registration Module
 * Extends mockData di lib/mockData.ts
 */

import type {
  Competition,
  CompetitionRegistration,
  RegistrationPlayer,
  UploadedDocument,
  DocumentRequirement,
  CompetitionRegulations,
} from "./types";
import { generatePlayers, mockClubs, mockEOs } from "@/lib/mockData";

/**
 * ============================================================================
 * MOCK COMPETITIONS - Extended dengan registration-specific fields
 * ============================================================================
 */

const competitionRegulations: CompetitionRegulations = {
  minPlayers: 18,
  maxPlayers: 23,
  minPlayerAge: 12,
  maxPlayerAge: 13,
  minSquadSize: 18,
};

const documentRequirements: DocumentRequirement[] = [
  {
    id: "doc-1",
    type: "manager-id",
    label: "KTP/ID Card Manager",
    required: true,
    acceptedFormats: ["pdf", "jpg", "jpeg", "png"],
    maxFileSize: 5 * 1024 * 1024,
    description: "Fotokopi KTP atau ID Card person dalam charge dari klub",
  },
  {
    id: "doc-2",
    type: "player-list",
    label: "Daftar Pemain (Squad List)",
    required: true,
    acceptedFormats: ["pdf", "xlsx", "xls", "doc", "docx"],
    maxFileSize: 5 * 1024 * 1024,
    description: "Daftar lengkap pemain yang terdaftar dengan format resmi",
  },
  {
    id: "doc-3",
    type: "payment-proof",
    label: "Bukti Pembayaran (Payment Proof)",
    required: true,
    acceptedFormats: ["pdf", "jpg", "jpeg", "png"],
    maxFileSize: 5 * 1024 * 1024,
    description: "Transfer bukti atau invoice pembayaran fees registrasi",
  },
  {
    id: "doc-4",
    type: "club-letter",
    label: "Surat Izin Resmi Klub (Club Official Letter)",
    required: false,
    acceptedFormats: ["pdf", "doc", "docx", "jpg", "jpeg", "png"],
    maxFileSize: 5 * 1024 * 1024,
    description: "Surat resmi dari klub dengan stempel kop surat klub",
  },
  {
    id: "doc-5",
    type: "player-id",
    label: "Fotokopi KTP Pemain",
    required: false,
    acceptedFormats: ["pdf", "jpg", "jpeg", "png"],
    maxFileSize: 5 * 1024 * 1024,
    description: "Fotokopi KTP/Passpor untuk semua pemain yang terdaftar",
  },
];

export const mockCompetitionsExtended: Competition[] = [
  {
    id: "comp-1",
    eoId: "eo-1",
    eoName: "PSSI Makassar",
    name: "Liga Makassar U13 2024",
    description: "Kompetisi liga tahunan untuk kategori usia 13 tahun di wilayah Makassar dengan standar nasional",
    format: "League",
    ageGroup: "U13",
    status: "Registration Open",
    registrationDeadline: "2024-02-28",
    startDate: "2024-03-01",
    endDate: "2024-06-30",
    registrationFee: 500000,
    maxWildcard: 2,
    currentClubs: 6,
    totalSlots: 8,
    slotsAvailable: 2,
    location: "Makassar, South Sulawesi",
    eoContact: "Ahmad Hamdan",
    eoPhone: "+62-411-123456",
    eoEmail: "info@pssi-makassar.id",
    regulations: competitionRegulations,
    documents: documentRequirements,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "comp-2",
    eoId: "eo-1",
    eoName: "PSSI Makassar",
    name: "Cup Makassar U15 2024",
    description: "Turnamen knockout bergengsi untuk kategori usia 15 tahun dengan hadiah menarik dan coverage media",
    format: "Knockout",
    ageGroup: "U15",
    status: "Registration Open",
    registrationDeadline: "2024-03-15",
    startDate: "2024-04-01",
    endDate: "2024-05-31",
    registrationFee: 750000,
    maxWildcard: 3,
    currentClubs: 12,
    totalSlots: 16,
    slotsAvailable: 4,
    location: "Makassar, South Sulawesi",
    eoContact: "Ahmad Hamdan",
    eoPhone: "+62-411-123456",
    eoEmail: "info@pssi-makassar.id",
    regulations: { ...competitionRegulations, minPlayerAge: 14, maxPlayerAge: 16 },
    documents: documentRequirements,
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "comp-3",
    eoId: "eo-1",
    eoName: "PSSI Makassar",
    name: "Piala Walikota U10 2024",
    description: "Festival sepak bola untuk kategori usia 10 tahun yang baru dibuka",
    format: "Group+KO",
    ageGroup: "U10",
    status: "Draft",
    registrationDeadline: "2024-06-15",
    startDate: "2024-07-01",
    endDate: "2024-08-31",
    registrationFee: 300000,
    maxWildcard: 1,
    currentClubs: 0,
    totalSlots: 12,
    slotsAvailable: 12,
    location: "Makassar, South Sulawesi",
    eoContact: "Ahmad Hamdan",
    eoPhone: "+62-411-123456",
    eoEmail: "info@pssi-makassar.id",
    regulations: { ...competitionRegulations, minPlayerAge: 9, maxPlayerAge: 10, maxPlayers: 20 },
    documents: documentRequirements,
    createdAt: "2024-01-25T10:00:00Z",
  },
  {
    id: "comp-4",
    eoId: "eo-5",
    eoName: "Jakarta Premier League",
    name: "Jakarta Super League U15 2024",
    description: "Liga elit Jakarta untuk kategori usia 15 tahun dengan kompetisi tingkat tinggi",
    format: "League",
    ageGroup: "U15",
    status: "Active",
    registrationDeadline: "2024-01-10",
    startDate: "2024-01-15",
    endDate: "2024-12-15",
    registrationFee: 1000000,
    maxWildcard: 2,
    currentClubs: 20,
    totalSlots: 20,
    slotsAvailable: 0,
    location: "Jakarta Pusat",
    eoContact: "Budi Hartono",
    eoPhone: "+62-21-9876543",
    eoEmail: "info@jakarta-premier.id",
    regulations: { ...competitionRegulations, minPlayerAge: 14, maxPlayerAge: 16 },
    documents: documentRequirements,
    createdAt: "2024-01-01T10:00:00Z",
  },
  {
    id: "comp-5",
    eoId: "eo-2",
    eoName: "Liga Surabaya FC",
    name: "Surabaya Cup U12 2024",
    description: "Piala Surabaya kelompok umur 12 tahun - Competition sudah selesai",
    format: "Group+KO",
    ageGroup: "U12",
    status: "Finished",
    registrationDeadline: "2024-12-15",
    startDate: "2024-01-01",
    endDate: "2024-02-28",
    registrationFee: 500000,
    maxWildcard: 2,
    currentClubs: 8,
    totalSlots: 8,
    slotsAvailable: 0,
    location: "Surabaya, East Java",
    eoContact: "Siti Rahma",
    eoPhone: "+62-31-555666",
    eoEmail: "info@surabaya-cup.id",
    regulations: { ...competitionRegulations, minPlayerAge: 11, maxPlayerAge: 12 },
    documents: documentRequirements,
    createdAt: "2023-12-01T10:00:00Z",
  },
];

/**
 * ============================================================================
 * MOCK REGISTRATIONS
 * ============================================================================
 */

export const mockRegistrationPlayers: RegistrationPlayer[] = [
  {
    id: "club1-reg-p1",
    playerId: "club-1-p1",
    name: "Budi Pratama",
    birthDate: "2010-05-15",
    age: 13,
    nationality: "Indonesia",
    idNumber: "737115051015001",
    position: "GK",
    shirtNumber: 1,
    height: 175,
    weight: 65,
    eligible: true,
  },
  {
    id: "club1-reg-p2",
    playerId: "club-1-p2",
    name: "Andi Santoso",
    birthDate: "2010-08-20",
    age: 13,
    nationality: "Indonesia",
    idNumber: "737115082010002",
    position: "CB",
    shirtNumber: 4,
    height: 172,
    weight: 62,
    eligible: true,
  },
  {
    id: "club1-reg-p3",
    playerId: "club-1-p3",
    name: "Rizky Wijaya",
    birthDate: "2011-02-10",
    age: 12,
    nationality: "Indonesia",
    idNumber: "737115021110003",
    position: "CB",
    shirtNumber: 5,
    height: 170,
    weight: 60,
    eligible: true,
  },
  {
    id: "club1-reg-p4",
    playerId: "club-1-p4",
    name: "Fajar Saputra",
    birthDate: "2010-11-30",
    age: 13,
    nationality: "Indonesia",
    idNumber: "737115113010004",
    position: "LB",
    shirtNumber: 3,
    height: 168,
    weight: 58,
    eligible: true,
  },
  {
    id: "club1-reg-p5",
    playerId: "club-1-p5",
    name: "Dimas Kusuma",
    birthDate: "2010-06-15",
    age: 13,
    nationality: "Indonesia",
    idNumber: "737115061510005",
    position: "RB",
    shirtNumber: 2,
    height: 169,
    weight: 59,
    eligible: true,
  },
];

export const mockUploadedDocuments: UploadedDocument[] = [
  {
    id: "doc-upload-1",
    type: "manager-id",
    fileName: "manager-ktp.pdf",
    fileSize: 2048000,
    fileType: "application/pdf",
    uploadedAt: "2024-02-15T14:30:00Z",
    status: "Approved",
    url: "https://storage.example.com/uploads/manager-ktp.pdf",
    storagePath: "/registrations/reg-1/manager-ktp.pdf",
  },
  {
    id: "doc-upload-2",
    type: "player-list",
    fileName: "squad-list-2024.xlsx",
    fileSize: 1024000,
    fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    uploadedAt: "2024-02-15T14:35:00Z",
    status: "Approved",
    url: "https://storage.example.com/uploads/squad-list-2024.xlsx",
    storagePath: "/registrations/reg-1/squad-list-2024.xlsx",
  },
  {
    id: "doc-upload-3",
    type: "payment-proof",
    fileName: "payment-proof.jpg",
    fileSize: 3072000,
    fileType: "image/jpeg",
    uploadedAt: "2024-02-15T14:40:00Z",
    status: "Pending",
    url: "https://storage.example.com/uploads/payment-proof.jpg",
    storagePath: "/registrations/reg-1/payment-proof.jpg",
    approvalNotes: "Menunggu verifikasi bank",
  },
];

export const mockCompetitionRegistrations: CompetitionRegistration[] = [
  {
    id: "reg-club1-comp1",
    clubId: "club-1",
    competitionId: "comp-1",
    club: {
      id: "club-1",
      name: "SSB Garuda Muda",
      city: "Makassar",
      address: "Jl. Hasanuddin No. 123, Makassar",
      contactPerson: "Ahmad Yani",
      contactPhone: "+62-812-1234567",
      contactEmail: "ahmad@garudamuda.id",
      founded: 2010,
      status: "Verified",
    },
    competition: mockCompetitionsExtended[0],
    status: "Approved",
    stepCompleted: 4,
    squad: mockRegistrationPlayers,
    documents: mockUploadedDocuments,
    createdAt: "2024-02-10T10:00:00Z",
    submittedAt: "2024-02-15T14:45:00Z",
    approvedAt: "2024-02-16T09:30:00Z",
    notes: "Semua dokumen sudah complete dan disetujui",
    internalNotes: "Klub sudah pernah berpartisipasi sebelumnya",
  },
  {
    id: "reg-club2-comp1",
    clubId: "club-2",
    competitionId: "comp-1",
    club: {
      id: "club-2",
      name: "SSB Bintang Timur",
      city: "Makassar",
      address: "Jl. Kuningan No. 45, Makassar",
      contactPerson: "Budi Santoso",
      contactPhone: "+62-812-2234567",
      contactEmail: "budi@bintangtimur.id",
      founded: 2012,
      status: "Verified",
    },
    competition: mockCompetitionsExtended[0],
    status: "Submitted",
    stepCompleted: 4,
    squad: mockRegistrationPlayers.slice(0, 3),
    documents: mockUploadedDocuments.slice(0, 2),
    createdAt: "2024-02-12T10:00:00Z",
    submittedAt: "2024-02-18T15:20:00Z",
    notes: "Menunggu approval dari EO",
    internalNotes: "",
  },
  {
    id: "reg-club1-comp2",
    clubId: "club-1",
    competitionId: "comp-2",
    club: {
      id: "club-1",
      name: "SSB Garuda Muda",
      city: "Makassar",
      address: "Jl. Hasanuddin No. 123, Makassar",
      contactPerson: "Ahmad Yani",
      contactPhone: "+62-812-1234567",
      contactEmail: "ahmad@garudamuda.id",
      founded: 2010,
      status: "Verified",
    },
    competition: mockCompetitionsExtended[1],
    status: "Draft",
    stepCompleted: 2,
    squad: mockRegistrationPlayers.slice(0, 5),
    documents: [],
    createdAt: "2024-03-01T10:00:00Z",
    notes: "Still in progress - player selection step",
    internalNotes: "",
  },
];
